### ISSUE TITLE
Setup Process for macOS is incorrect

### ISSUE THREAD

**Issue by DWVoid** [robomasterhkust/RMTutorialF103#1]
1. The default brew repository contains no arm-non-eabi-gcc. The px4 repository should be imported first, and px4/px4-dev should be installed.
2. The brew repository has no formula named 'openocd'. The correct name should be 'open-ocd'.

**Comment by alexacw** [comment]
sorry for the inconvenience caused, as I don't have a mac and that section was edited by @syangav 
we will try to fix that asap

**Comment by syangav** [comment]
I am working on it. Thanks for the feedback anyway.

**Comment by syangav** [comment]
README updated. Thanks for everybody's participation, especially @DWVoid
